import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import SplashCursor from "@/components/SplashCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JS Visual Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>

      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased `}
      >
        <body className="min-h-full flex flex-col overflow-x-hidden">
          {/* <SplashCursor
            DENSITY_DISSIPATION={3.5}
            VELOCITY_DISSIPATION={2}
            PRESSURE={0.1}
            CURL={3}
            SPLAT_RADIUS={0.2}
            SPLAT_FORCE={6000}
            COLOR_UPDATE_SPEED={10}
            SHADING
            RAINBOW_MODE={false}
            COLOR="#a57dca"
         /> */}
          <Navbar />

          {children}

        </body>
      </html>
    </>
  );
}
